%YAML:1.0

# 数据存放路径
PGRFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/ladybug_12193151_20180914_152750-000000.pgr"
velodyneFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/2018-09-14-15-27-50.pcap"
flea2Path: "F:/KYXZ2020/G/data/data_20180914/Raw-011/Camera/"
lmsFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/2018-09-14-15-27-49.lms"
gpsFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/gpslog2018-09-14-15-27-50.log-GPS.csv"
imuFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/gpslog2018-09-14-15-27-50.log-IMU.csv"

# 参数文件路径
veloInstrinsicParamsFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/CalibParams/HDL32-I.txt"
veloExtrinsicParamsFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/CalibParams/HDL32-E.txt"
lmsExtrinsicParamsFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/CalibParams/Laser.txt"
ladybugCalibFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/CalibParams/Ladybug.txt"
flea2CalibFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/CalibParams/Camera.camera"
flea2ExtrinsicParamsFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/CalibParams/Laser.txt"
gpsExtrinsicParamsFilename: "F:/KYXZ2020/G/data/data_20180914/Raw-011/CalibParams/GPS.txt"


#生成目标文件
gtFile: "gt.csv"

terror_const: 0.0
terror_linear: 0.001403366795423015
terror_time_ori: 55670219

isLMSReverse: 1
gpsMethod: "GPS_NEAREST"
#gpsMethod: "GPS_INTERPOLATED"

#skipFrames: 0
#startTime: "57720847"
startTime: "58600000"
responseTime: 10

useBGR: 0

refineStep: 0
refineUID: 0
refineObjClass: 'V'

minValidVeloHeight: 0.0
maxValidVeloHeight: 1.0
veloColor: 0

minImageVisibleHeight: 25