%YAML:1.0
PGRFilename: "E:/KYXZ2020/G/data/data_20201011/data-1/ladybug_12193151_20201011_111126-000000.pgr"
velodyneFilename: "E:/KYXZ2020/G/data/data_20201011/data-1/HDL32.pcap"
flea2Path: "E:/KYXZ2020/G/data/data_20201011/data-1/Camera/"
lmsFilename: "E:/KYXZ2020/G/data/data_20201011/data-1/URG.lms"
gpsFilename: "E:/KYXZ2020/G/data/data_20201011/data-1/GPS.csv"
imuFilename: "E:/KYXZ2020/G/data/data_20201011/data-1/IMU.csv"

# 参数文件路径
veloInstrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201011/CalibParams/20201010-HDL32-I.txt"
veloExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201011/CalibParams/20201010-HDL32-E.txt"
lmsExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201011/CalibParams/20201010-Laser.txt"
ladybugCalibFilename: "E:/KYXZ2020/G/data/data_20201011/CalibParams/20201010-001-Ladybug.txt"
flea2CalibFilename: "E:/KYXZ2020/G/data/data_20201011/CalibParams/20201010-Camera.camera"
flea2ExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201011/CalibParams/20201010-Laser.txt"
gpsExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201011/CalibParams/20201010-GPS.txt"

gtFile: "gt.csv"

terror_const: 0
terror_linear: 0

isLMSReverse: 1
gpsMethod: "GPS_NEAREST"
#gpsMethod: "GPS_INTERPOLATED"

#v1 40293263 (uid 0)
#h1 40370525 (uid 1)

useBGR: 1

startTime: "40324487"
responseTime: 10

refineStep: 0
refineUID: 0
refineObjClass: 'H'

minValidVeloHeight: 0.0
maxValidVeloHeight: 1.0
veloColor: 0

minImageVisibleHeight: 25