%YAML:1.0
PGRFilename: "C:/Users/chen/Desktop/2/ladybug_12193151_20180726_135050-000000.pgr"
#velodyneFilename: "F:/kyxz2018/0627/Afternoon/52018-06-27-10-41-00.pcap"
velodyneFilename:"C:/Users/chen/Desktop/2/2018-07-26-13-50-50.pcap"
#velodyneFilename: "F:/zhuangjisuo/testdata005/2018-06-27-14-03-38.pcap"

#flea2PatE: "C:/FastRWBuffer/LabData/kyxz2018/20180627/4/2018_06_27_10_41_02/"
flea2Path: "C:/Users/chen/Desktop/2/2018_07_26_13_50_51/"
lmsFilename: "C:/Users/chen/Desktop/2/2018-07-26-13-50-49.lms"
gpsFilename: "C:/Users/chen/Desktop/2/gpslog2018-07-26-13-50-49.log-GPS.csv"
imuFilename: "C:/Users/chen/Desktop/2/gpslog2018-07-26-13-50-49.log-IMU.csv"

veloInstrinsicParamsFilename: "C:/Users/chen/Desktop/CalibParams/Sampledata-001-HDL32-I.txt"
veloExtrinsicParamsFilename: "C:/Users/chen/Desktop/CalibParams/Sampledata-001-HDL32-E.txt"
lmsExtrinsicParamsFilename: "C:/Users/chen/Desktop/CalibParams/Sampledata-001-Laser.txt"
ladybugCalibFilename: "C:/Users/chen/Desktop/CalibParams/Sampledata-001-Ladybug.txt"
flea2CalibFilename: "C:/Users/chen/Desktop/CalibParams/Sampledata-001-Camera.camera"
#flea2CalibFilename: "C:/Users/chen/Desktop/CalibParams/test_ex.camera"
flea2ExtrinsicParamsFilename: "C:/Users/chen/Desktop/CalibParams/Sampledata-001-Laser.txt"
gpsExtrinsicParamsFilename: "C:/Users/chen/Desktop/CalibParams/Sampledata-001-GPS.txt"

#生成目标文件
gtFile: "gt.csv"

terror_const: 0
terror_linear: 0

isLMSReverse: 1
gpsMethod: "GPS_NEAREST"
#gpsMethod: "GPS_INTERPOLATED"


#skipFrames: 0n

#startTime: "49885000"
startTime: "50020000"
responseTime: 10

#0~3
refineStep: 3
refineUID: 18
refineObjClass: 'V'

#
minValidVeloHeight: 0.0
maxValidVeloHeight: 2.0
veloColor: 0