%YAML:1.0
PGRFilename: "K:/LabData/kyxz2018/2018Eval/OurRawData/Raw/LadybugRaw/ladybug_12193151_20180914_152750-000000.pgr"
velodyneFilename:"K:/LabData/kyxz2018/2018Eval/OurRawData/2018-09-14-15-27-50.pcap"

flea2Path: "K:/LabData/kyxz2018/2018Eval/OurRawData/MonoImages_2018_09_14_15_27_51/"
lmsFilename: "K:/LabData/kyxz2018/2018Eval/OurRawData/2018-09-14-15-27-49.lms"
gpsFilename: "K:/LabData/kyxz2018/2018Eval/OurRawData/gpslog2018-09-14-15-27-50.log-GPS.csv"
imuFilename: "K:/LabData/kyxz2018/2018Eval/OurRawData/gpslog2018-09-14-15-27-50.log-IMU.csv"

veloInstrinsicParamsFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/Sampledata-001-HDL32-I.txt"
veloExtrinsicParamsFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/Sampledata-001-HDL32-E.txt"
lmsExtrinsicParamsFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/Sampledata-001-Laser.txt"
ladybugCalibFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/Sampledata-001-Ladybug.txt"
flea2CalibFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/Sampledata-001-Camera.camera"
#flea2CalibFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/test_ex.camera"
flea2ExtrinsicParamsFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/Sampledata-001-Laser.txt"
gpsExtrinsicParamsFilename: "K:/LabData/kyxz2018/20180727/calib/CalibParams/Sampledata-001-GPS.txt"

#生成目标文件
gtFile: "gt.csv"

terror_const: 0
terror_linear: 0

isLMSReverse: 1
gpsMethod: "GPS_NEAREST"
#gpsMethod: "GPS_INTERPOLATED"

#h1 220 (uid 0)
#h2 260 (uid 2)
#h3 1150 (uid 6)
#h4 1600 (uid 8)
#h5 440 (uid 10)
#b1 invisible
#b2 400 (uid 12)
#b3 800 (uid 4)
#skipFrames: 0
#startTime: "0"
startTime: "56783759"
responseTime: 10

refineStep: 0
refineUID: 14
refineObjClass: 'V'

minValidVeloHeight: 0.0
maxValidVeloHeight: 1.0
veloColor: 0

minImageVisibleHeight: 25