%YAML:1.0
# 数据存放路径
PGRFilename: "E:/KYXZ2020/G/data/data_20201010/data-Calib/ladybug_12193151_20201010_144334-000000.pgr"
velodyneFilename: "E:/KYXZ2020/G/data/data_20201010/data-Calib/HDL32.pcap"
flea2Path: "E:/KYXZ2020/G/data/data_20201010/data-Calib/Camera/"
lmsFilename: "E:/KYXZ2020/G/data/data_20201010/data-Calib/URG.lms"
gpsFilename: "E:/KYXZ2020/G/data/data_20201010/data-Calib/GPS.csv"
imuFilename: "E:/KYXZ2020/G/data/data_20201010/data-Calib/IMU.csv"

# 参数文件路径
veloInstrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201010/CalibParams/20201010-HDL32-I.txt"
veloExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201010/CalibParams/20201010-HDL32-E.txt"
lmsExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201010/CalibParams/20201010-Laser.txt"
ladybugCalibFilename: "E:/KYXZ2020/G/data/data_20201010/CalibParams/20201010-001-Ladybug.txt"
flea2CalibFilename: "E:/KYXZ2020/G/data/data_20201010/CalibParams/20201010-Camera.camera"
flea2ExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201010/CalibParams/20201010-Laser.txt"
gpsExtrinsicParamsFilename: "E:/KYXZ2020/G/data/data_20201010/CalibParams/20201010-GPS.txt"

#生成目标文件
gtFile: "gt.csv"

terror_const: 0
terror_linear: 0

isLMSReverse: 1
gpsMethod: "GPS_NEAREST"
#gpsMethod: "GPS_INTERPOLATED"

startTime: "0"
responseTime: 10

refineStep: 1
refineUID: 0
refineObjClass: 'V'

minValidVeloHeight: 0.0
maxValidVeloHeight: 1.0
veloColor: 0

minImageVisibleHeight: 25